(test
 (name test_starling)
 (libraries starling alcotest hex))

(test
 (name test_multistream)
 (libraries starling alcotest eio eio.unix eio_main))

(test
 (name test_noise)
 (libraries starling alcotest hex mirage-crypto))

(test
 (name test_noise_handshake)
 (libraries starling alcotest hex eio eio.unix eio_main mirage-crypto-rng.unix))

(test
 (name test_yamux)
 (libraries starling alcotest hex eio eio.unix eio_main mirage-crypto-rng.unix))

(test
 (name test_mvp)
 (libraries starling alcotest hex eio eio.unix eio_main mirage-crypto-rng.unix))
